name: spotlight_effects
description: "The Spotlight Flutter package enables developers to create captivating spotlight effects in their applications, allowing for easy highlighting."
version: 0.0.1
homepage: https://github.com/Nikhil-ig/Spotlight-Effect-Flutter-Package

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: